var a=10;
var b=20;
var c=a+b;
var s=a-b;
var m=a*b;
var d=a/b;
console.log("Value of a:"+a);
console.log("Value of b:"+b);
console.log("Addition is:"+c);
console.log("Subtraction is:"+s);
console.log("Multiplication is:"+m);
console.log("Division is:"+d);